import { Option } from 'fp-ts/lib/Option';
import { string, number, type } from 'io-ts';
import { createOptionFromNullable } from 'io-ts-types';

export type LELodasoftCommonModelsLeadsProviderModelsLeadPointLead = {
	product: Option<string>;
	loaN_VAL: Option<number>;
	esT_VAL: Option<number>;
	loaN_TYPE: Option<string>;
	dowN_PMT: Option<number>;
	proP_ZIP: Option<string>;
	proP_DESC: Option<string>;
	speC_HOME: Option<string>;
	proP_ST: Option<string>;
	proP_PURP: Option<string>;
	proP_AREA: Option<string>;
	buY_TIMEFRAME: Option<string>;
	purchasE_CONTRACT: Option<string>;
	agenT_FOUND: Option<string>;
	agenT_NAME: Option<string>;
	agenT_PHONE: Option<string>;
	agenT_COMPANY: Option<string>;
	agenT_EMAIL: Option<string>;
	agenT_ADDRESS: Option<string>;
	agenT_CITY: Option<string>;
	agenT_STATE: Option<string>;
	agenT_ZIP: Option<string>;
	agenT_STATUS: Option<string>;
	agenT2_NAME: Option<string>;
	agenT2_COMPANY: Option<string>;
	agenT2_EMAIL: Option<string>;
	agenT2_PHONE: Option<string>;
	agenT2_ADDRESS: Option<string>;
	agenT2_CITY: Option<string>;
	agenT2_STATE: Option<string>;
	agenT2_ZIP: Option<string>;
	agenT3_NAME: Option<string>;
	agenT3_PHONE: Option<string>;
	agenT3_COMPANY: Option<string>;
	agenT3_EMAIL: Option<string>;
	agenT3_ADDRESS: Option<string>;
	agenT2_STATUS: Option<string>;
	agenT3_CITY: Option<string>;
	agenT3_ZIP: Option<string>;
	agenT3_STATUS: Option<string>;
	agenT4_NAME: Option<string>;
	agenT4_PHONE: Option<string>;
	agenT4_COMPANY: Option<string>;
	agenT4_EMAIL: Option<string>;
	agenT4_ADDRESS: Option<string>;
	agenT4_CITY: Option<string>;
	agenT4_STATE: Option<string>;
	agenT4_ZIP: Option<string>;
	agenT4_STATUS: Option<string>;
	proP_URL: Option<string>;
	proP_BEDS: Option<string>;
	proP_BATHS: Option<string>;
	proP_SQFT: Option<string>;
	agenT3_STATE: Option<string>;
	creD_GRADE: Option<string>;
	income: Option<string>;
	miN_PAY: Option<string>;
	ocC_STAT: Option<string>;
	bkcy: Option<string>;
	firsT_BUYER: Option<string>;
	fhA_BANK_FORECLOSURE: Option<string>;
	annuaL_VERIFIABLE_INCOME: Option<string>;
	vA_STATUS: Option<string>;
	nuM_MORTGAGE_LATES: Option<string>;
	fname: Option<string>;
	lname: Option<string>;
	email: Option<string>;
	prI_PHON: Option<string>;
	seC_PHON: Option<string>;
	preF_CALLTIME: Option<string>;
	address: Option<string>;
	city: Option<string>;
	state: Option<string>;
	zip: Option<string>;
	ssn: Option<string>;
	custom: Option<string>;
	calleR_ID: Option<string>;
	agE_ATLEAST_62: Option<string>;
	dobmm: Option<string>;
	dobdd: Option<string>;
	dobyyyy: Option<string>;
	ssN_CHECK: Option<string>;
	consumeR_COMMENTS: Option<string>;
	language: Option<string>;
};
export const LELodasoftCommonModelsLeadsProviderModelsLeadPointLeadIO = type({
	product: createOptionFromNullable(string),
	loaN_VAL: createOptionFromNullable(number),
	esT_VAL: createOptionFromNullable(number),
	loaN_TYPE: createOptionFromNullable(string),
	dowN_PMT: createOptionFromNullable(number),
	proP_ZIP: createOptionFromNullable(string),
	proP_DESC: createOptionFromNullable(string),
	speC_HOME: createOptionFromNullable(string),
	proP_ST: createOptionFromNullable(string),
	proP_PURP: createOptionFromNullable(string),
	proP_AREA: createOptionFromNullable(string),
	buY_TIMEFRAME: createOptionFromNullable(string),
	purchasE_CONTRACT: createOptionFromNullable(string),
	agenT_FOUND: createOptionFromNullable(string),
	agenT_NAME: createOptionFromNullable(string),
	agenT_PHONE: createOptionFromNullable(string),
	agenT_COMPANY: createOptionFromNullable(string),
	agenT_EMAIL: createOptionFromNullable(string),
	agenT_ADDRESS: createOptionFromNullable(string),
	agenT_CITY: createOptionFromNullable(string),
	agenT_STATE: createOptionFromNullable(string),
	agenT_ZIP: createOptionFromNullable(string),
	agenT_STATUS: createOptionFromNullable(string),
	agenT2_NAME: createOptionFromNullable(string),
	agenT2_COMPANY: createOptionFromNullable(string),
	agenT2_EMAIL: createOptionFromNullable(string),
	agenT2_PHONE: createOptionFromNullable(string),
	agenT2_ADDRESS: createOptionFromNullable(string),
	agenT2_CITY: createOptionFromNullable(string),
	agenT2_STATE: createOptionFromNullable(string),
	agenT2_ZIP: createOptionFromNullable(string),
	agenT3_NAME: createOptionFromNullable(string),
	agenT3_PHONE: createOptionFromNullable(string),
	agenT3_COMPANY: createOptionFromNullable(string),
	agenT3_EMAIL: createOptionFromNullable(string),
	agenT3_ADDRESS: createOptionFromNullable(string),
	agenT2_STATUS: createOptionFromNullable(string),
	agenT3_CITY: createOptionFromNullable(string),
	agenT3_ZIP: createOptionFromNullable(string),
	agenT3_STATUS: createOptionFromNullable(string),
	agenT4_NAME: createOptionFromNullable(string),
	agenT4_PHONE: createOptionFromNullable(string),
	agenT4_COMPANY: createOptionFromNullable(string),
	agenT4_EMAIL: createOptionFromNullable(string),
	agenT4_ADDRESS: createOptionFromNullable(string),
	agenT4_CITY: createOptionFromNullable(string),
	agenT4_STATE: createOptionFromNullable(string),
	agenT4_ZIP: createOptionFromNullable(string),
	agenT4_STATUS: createOptionFromNullable(string),
	proP_URL: createOptionFromNullable(string),
	proP_BEDS: createOptionFromNullable(string),
	proP_BATHS: createOptionFromNullable(string),
	proP_SQFT: createOptionFromNullable(string),
	agenT3_STATE: createOptionFromNullable(string),
	creD_GRADE: createOptionFromNullable(string),
	income: createOptionFromNullable(string),
	miN_PAY: createOptionFromNullable(string),
	ocC_STAT: createOptionFromNullable(string),
	bkcy: createOptionFromNullable(string),
	firsT_BUYER: createOptionFromNullable(string),
	fhA_BANK_FORECLOSURE: createOptionFromNullable(string),
	annuaL_VERIFIABLE_INCOME: createOptionFromNullable(string),
	vA_STATUS: createOptionFromNullable(string),
	nuM_MORTGAGE_LATES: createOptionFromNullable(string),
	fname: createOptionFromNullable(string),
	lname: createOptionFromNullable(string),
	email: createOptionFromNullable(string),
	prI_PHON: createOptionFromNullable(string),
	seC_PHON: createOptionFromNullable(string),
	preF_CALLTIME: createOptionFromNullable(string),
	address: createOptionFromNullable(string),
	city: createOptionFromNullable(string),
	state: createOptionFromNullable(string),
	zip: createOptionFromNullable(string),
	ssn: createOptionFromNullable(string),
	custom: createOptionFromNullable(string),
	calleR_ID: createOptionFromNullable(string),
	agE_ATLEAST_62: createOptionFromNullable(string),
	dobmm: createOptionFromNullable(string),
	dobdd: createOptionFromNullable(string),
	dobyyyy: createOptionFromNullable(string),
	ssN_CHECK: createOptionFromNullable(string),
	consumeR_COMMENTS: createOptionFromNullable(string),
	language: createOptionFromNullable(string),
});
