import { Option } from 'fp-ts/lib/Option';
import { number, string, array, type } from 'io-ts';
import { createOptionFromNullable, DateFromISOString } from 'io-ts-types';

export type LELodasoftCommonModelsLeadsLeadViewModel = {
	leadId: Option<number>;
	borrowerId: Option<number>;
	applicationId: Option<number>;
	firstName: Option<string>;
	lastName: Option<string>;
	socialSecurityNumber: Option<string>;
	birthDate: Option<Date>;
	email: Option<string>;
	phone: Option<string>;
	workPhone: Option<string>;
	fax: Option<string>;
	mailingAddress1: Option<string>;
	mailingAddress2: Option<string>;
	mailingCity: Option<string>;
	mailingState: Option<string>;
	mailingZip: Option<string>;
	creditScore: Option<number>;
	subjectPropertyAddress1: Option<string>;
	subjectPropertyAddress2: Option<string>;
	subjectPropertyCity: Option<string>;
	subjectPropertyState: Option<string>;
	subjectPropertyZip: Option<string>;
	loanAmount: Option<number>;
	appraisedValue: Option<number>;
	cashOutAmount: Option<number>;
	downPayment: Option<number>;
	interestRate: Option<number>;
	loanTypeId: Option<number>;
	loanPurposeId: Option<number>;
	currentLoanUnpaidPrincipalBalance: Option<number>;
	currentLoanEstimatedValue: Option<number>;
	currentLoanInterestRate: Option<number>;
	currentLoanTerm: Option<number>;
	leadContactUserId: Option<string>;
	appointmentDate: Option<Date>;
	appointmentDescription: Option<string>;
	appointmentNotes: Option<string>;
	customData1: Option<string>;
	customData2: Option<string>;
	customData3: Option<string>;
	customData4: Option<string>;
	customData5: Option<string>;
	customData6: Option<string>;
	customData7: Option<string>;
	customData8: Option<string>;
	customData9: Option<string>;
	customData10: Option<string>;
	leadCampaignId: Option<number>;
	leadStatusId: Option<number>;
	referralSource: Option<number>;
	leadSource: Option<string>;
	losRefNumber: Option<string>;
	internalNotes: Option<string>;
	postLeadRequestJson: Option<string>;
	lastAttemptedContact: Option<Date>;
	lastSuccessfulContact: Option<Date>;
	leadListIds: Option<Array<number>>;
	companyId: Option<number>;
	insertedBy: Option<string>;
	dateInserted: Option<Date>;
	updatedBy: Option<string>;
	dateUpdated: Option<Date>;
};
export const LELodasoftCommonModelsLeadsLeadViewModelIO = type({
	leadId: createOptionFromNullable(number),
	borrowerId: createOptionFromNullable(number),
	applicationId: createOptionFromNullable(number),
	firstName: createOptionFromNullable(string),
	lastName: createOptionFromNullable(string),
	socialSecurityNumber: createOptionFromNullable(string),
	birthDate: createOptionFromNullable(DateFromISOString),
	email: createOptionFromNullable(string),
	phone: createOptionFromNullable(string),
	workPhone: createOptionFromNullable(string),
	fax: createOptionFromNullable(string),
	mailingAddress1: createOptionFromNullable(string),
	mailingAddress2: createOptionFromNullable(string),
	mailingCity: createOptionFromNullable(string),
	mailingState: createOptionFromNullable(string),
	mailingZip: createOptionFromNullable(string),
	creditScore: createOptionFromNullable(number),
	subjectPropertyAddress1: createOptionFromNullable(string),
	subjectPropertyAddress2: createOptionFromNullable(string),
	subjectPropertyCity: createOptionFromNullable(string),
	subjectPropertyState: createOptionFromNullable(string),
	subjectPropertyZip: createOptionFromNullable(string),
	loanAmount: createOptionFromNullable(number),
	appraisedValue: createOptionFromNullable(number),
	cashOutAmount: createOptionFromNullable(number),
	downPayment: createOptionFromNullable(number),
	interestRate: createOptionFromNullable(number),
	loanTypeId: createOptionFromNullable(number),
	loanPurposeId: createOptionFromNullable(number),
	currentLoanUnpaidPrincipalBalance: createOptionFromNullable(number),
	currentLoanEstimatedValue: createOptionFromNullable(number),
	currentLoanInterestRate: createOptionFromNullable(number),
	currentLoanTerm: createOptionFromNullable(number),
	leadContactUserId: createOptionFromNullable(string),
	appointmentDate: createOptionFromNullable(DateFromISOString),
	appointmentDescription: createOptionFromNullable(string),
	appointmentNotes: createOptionFromNullable(string),
	customData1: createOptionFromNullable(string),
	customData2: createOptionFromNullable(string),
	customData3: createOptionFromNullable(string),
	customData4: createOptionFromNullable(string),
	customData5: createOptionFromNullable(string),
	customData6: createOptionFromNullable(string),
	customData7: createOptionFromNullable(string),
	customData8: createOptionFromNullable(string),
	customData9: createOptionFromNullable(string),
	customData10: createOptionFromNullable(string),
	leadCampaignId: createOptionFromNullable(number),
	leadStatusId: createOptionFromNullable(number),
	referralSource: createOptionFromNullable(number),
	leadSource: createOptionFromNullable(string),
	losRefNumber: createOptionFromNullable(string),
	internalNotes: createOptionFromNullable(string),
	postLeadRequestJson: createOptionFromNullable(string),
	lastAttemptedContact: createOptionFromNullable(DateFromISOString),
	lastSuccessfulContact: createOptionFromNullable(DateFromISOString),
	leadListIds: createOptionFromNullable(array(number)),
	companyId: createOptionFromNullable(number),
	insertedBy: createOptionFromNullable(string),
	dateInserted: createOptionFromNullable(DateFromISOString),
	updatedBy: createOptionFromNullable(string),
	dateUpdated: createOptionFromNullable(DateFromISOString),
});
