import { LELodasoftDataAccessModelsAdminBorrowerFileDto } from '../definitions/LELodasoftDataAccessModelsAdminBorrowerFileDto';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftApiModelsBorrowerLoanDocTask_DashBoardView = {
    loanDocTaskId: Option<number>;
    applicationId: Option<number>;
    leadId: Option<number>;
    loanDocId: Option<number>;
    primaryBorrowerId: Option<number>;
    borrowerId: Option<number>;
    fullName: Option<string>;
    applicationName: Option<string>;
    taskId: Option<number>;
    customTaskId: Option<number>;
    responsibleParty: Option<string>;
    requestedBy: Option<string>;
    note: Option<string>;
    status: Option<'Pending' | 'Submitted' | 'Rejected' | 'Approved' | 'NotApplicable' | 'Requested' | 'Completed' | 'ReviewReady'>;
    taskStatus: Option<string>;
    taskPriority: Option<'Low' | 'Normal' | 'High' | 'Immediate'>;
    taskType: Option<'RequestDocument' | 'ViewDocument' | 'AcknowledgeReceipt' | 'EsignDocument' | 'RequestInformation' | 'PerformAction' | 'OnlineApplication' | 'DigitalAssetVerification'>;
    documentTypeId: Option<number>;
    docTypeText: Option<string>;
    description: Option<string>;
    dueDays: Option<number>;
    requestDate: Option<Date>;
    dueDate: Option<Date>;
    followUp: Option<Date>;
    completeDate: Option<Date>;
    submittedDate: Option<Date>;
    expirationDate: Option<Date>;
    userId: Option<string>;
    roleId: Option<number>;
    requestBorrower: Option<boolean>;
    loading: Option<boolean>;
    borrowerNote: Option<string>;
    condition: Option<boolean>;
    conditionStatus: Option<'ConditionPending' | 'ConditionCleared' | 'ConditionReOpened'>;
    conditionType: Option<'PTS' | 'PTD' | 'PTF' | 'PTC'>;
    docFiles: Option<Array<LELodasoftDataAccessModelsAdminBorrowerFileDto>>;
    notifyPartyId: Option<string>;
    requiresReview: Option<boolean>;
    reviewPartyId: Option<string>;
    borrowerFacingNote: Option<string>;
    hasTemplateDocument: Option<boolean>;
    templateDocumentUrl: Option<string>;
};
export declare const LELodasoftApiModelsBorrowerLoanDocTask_DashBoardViewIO: import("io-ts").TypeC<{
    loanDocTaskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    applicationId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    leadId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    loanDocId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    primaryBorrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    borrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    fullName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    applicationName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    taskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    customTaskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    responsibleParty: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    requestedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    note: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    status: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        Pending: null;
        Submitted: null;
        Rejected: null;
        Approved: null;
        NotApplicable: null;
        Requested: null;
        Completed: null;
        ReviewReady: null;
    }>>;
    taskStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    taskPriority: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        Low: null;
        Normal: null;
        High: null;
        Immediate: null;
    }>>;
    taskType: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        RequestDocument: null;
        ViewDocument: null;
        AcknowledgeReceipt: null;
        EsignDocument: null;
        RequestInformation: null;
        PerformAction: null;
        OnlineApplication: null;
        DigitalAssetVerification: null;
    }>>;
    documentTypeId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    docTypeText: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    description: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dueDays: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    requestDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    dueDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    followUp: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    completeDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    submittedDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    expirationDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    roleId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    requestBorrower: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    loading: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    borrowerNote: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    condition: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    conditionStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        ConditionPending: null;
        ConditionCleared: null;
        ConditionReOpened: null;
    }>>;
    conditionType: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        PTS: null;
        PTD: null;
        PTF: null;
        PTC: null;
    }>>;
    docFiles: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").TypeC<{
        guid: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        loanDocId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        fileName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        note: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        borrowerNote: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        condition: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        createDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        expirationDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        active: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    }>>>;
    notifyPartyId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    requiresReview: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    reviewPartyId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    borrowerFacingNote: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    hasTemplateDocument: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    templateDocumentUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
}>;
