import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsConfigurationDocumentTemplateFieldViewModel = {
    documentTemplateFieldId: Option<number>;
    documentTemplateId: Option<number>;
    fieldKey: Option<string>;
    fieldType: Option<'Unspecified' | 'Text' | 'CheckBox' | 'RadioButton'>;
    displayName: Option<string>;
    globalMergeFieldKey: Option<string>;
    defaultValue: Option<string>;
    visible: Option<boolean>;
    editable: Option<boolean>;
    documentTemplatePageId: Option<number>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsConfigurationDocumentTemplateFieldViewModelIO: import("io-ts").TypeC<{
    documentTemplateFieldId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    documentTemplateId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    fieldKey: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    fieldType: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        Unspecified: null;
        Text: null;
        CheckBox: null;
        RadioButton: null;
    }>>;
    displayName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    globalMergeFieldKey: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    defaultValue: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    visible: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    editable: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    documentTemplatePageId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
