import { LELodasoftCommonModelsConfigurationApplicationViewModel } from '../definitions/LELodasoftCommonModelsConfigurationApplicationViewModel';
import { LELodasoftDataAccessDbModelsAdminBorrowerModel } from '../definitions/LELodasoftDataAccessDbModelsAdminBorrowerModel';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftApiModelsBorrowerNewApplicationRequest = {
    application: Option<LELodasoftCommonModelsConfigurationApplicationViewModel>;
    internalContactGroupNumber: Option<string>;
    coBorrower: Option<LELodasoftDataAccessDbModelsAdminBorrowerModel>;
};
export declare const LELodasoftApiModelsBorrowerNewApplicationRequestIO: import("io-ts").TypeC<{
    application: import("io-ts-types").OptionFromNullableC<import("io-ts").TypeC<{
        applicationId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        primaryBorrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        loanStatusId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        loanTypeId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        loanPurposeId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        customDataId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        losIdentifier: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        refNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        loanAmount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        mipAmount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        cashOutAmount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        subordinateLienAmount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        purchasePrice: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        presentValue: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        downAmount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        rate: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        productId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        lenderId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        term: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        estimatedClosingDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        lockExpirationDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        cdIssueDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        cdSignedDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        originationDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        mailingStreet: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingPOBox: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingCity: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingState: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingZip: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateCreate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        referralSource: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    }>>;
    internalContactGroupNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    coBorrower: import("io-ts-types").OptionFromNullableC<import("io-ts").TypeC<{
        borrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        firstName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        middleName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        lastName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        birthDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        socialSecNum: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        borrowerContact: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        creditScore: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        alertViaSms: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        mobilePhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        workPhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        extPhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        fax: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        email: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        assistantName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        assistantPhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        doNotCall: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        doNotEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        mailingStreet: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingPOBox: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingCity: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingState: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        mailingZip: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateCreateBorrower: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        creditMonitoringStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
            Unset: null;
            Active: null;
            Disabled: null;
        }>>;
        companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    }>>;
}>;
