import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsOnlineAppOnlineAppProgressViewModel = {
    id: Option<number>;
    applicationId: Option<number>;
    mortgageId: Option<number>;
    currentStatus: Option<number>;
    currentStatusDatetime: Option<Date>;
    lastSuccessfulStatus: Option<number>;
    lastSuccessfulStatusDatetime: Option<Date>;
    currentSessionId: Option<string>;
    sessionCount: Option<number>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsOnlineAppOnlineAppProgressViewModelIO: import("io-ts").TypeC<{
    id: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    applicationId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    mortgageId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    currentStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    currentStatusDatetime: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    lastSuccessfulStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    lastSuccessfulStatusDatetime: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    currentSessionId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    sessionCount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
