"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LELodasoftCommonModelsMortgageAddressViewModel_1 = require("../definitions/LELodasoftCommonModelsMortgageAddressViewModel");
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsMortgageAssetViewModelIO = io_ts_1.type({
    assetId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    borrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    addressId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    assetType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Automobile: null,
        Bond: null,
        BridgeLoanNotDeposited: null,
        Cash: null,
        CertificateOfDepositTimeDeposit: null,
        CheckingAccount: null,
        EarnestMoneyCashDepositTowardPurchase: null,
        GiftsTotal: null,
        GiftsNotDeposited: null,
        LifeInsurance: null,
        MoneyMarketFund: null,
        MutualFund: null,
        NetWorthOfBusinessOwned: null,
        OtherLiquidAssets: null,
        OtherNonLiquidAssets: null,
        PendingNetSaleProceedsFromRealEstateAssets: null,
        RelocationMoney: null,
        RetirementFund: null,
        SaleOtherAssets: null,
        SavingsAccount: null,
        SecuredBorrowedFundsNotDeposited: null,
        Stock: null,
        TrustAccount: null,
    })),
    cashMarketValue: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    accountNumber: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    depository: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    makeModel: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    year: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    disposition: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    amountOfMortgageLien: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    morgagePayment: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    gross: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    netRentalIncome: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insMainTaxMisc: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    address: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsMortgageAddressViewModel_1.LELodasoftCommonModelsMortgageAddressViewModelIO),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insertedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    updatedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateUpdated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftCommonModelsMortgageAssetViewModel.js.map