"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsConfigurationApplicationViewModelIO = io_ts_1.type({
    applicationId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    userId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    primaryBorrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanStatusId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanTypeId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanPurposeId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    customDataId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    losIdentifier: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    refNumber: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    loanAmount: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    mipAmount: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    cashOutAmount: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    subordinateLienAmount: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    purchasePrice: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    presentValue: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    downAmount: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    rate: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    productId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    lenderId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    term: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    estimatedClosingDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    lockExpirationDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    cdIssueDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    cdSignedDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    originationDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    mailingStreet: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingPOBox: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingCity: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingState: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingZip: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateCreate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    referralSource: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insertedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    updatedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateUpdated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftCommonModelsConfigurationApplicationViewModel.js.map