import { LELodasoftCommonModelsAdminAutomatedEmailViewModel } from '../definitions/LELodasoftCommonModelsAdminAutomatedEmailViewModel';
import { LELodasoftCommonModelsAdminEmailCampaignLoanStatusTriggerViewModel } from '../definitions/LELodasoftCommonModelsAdminEmailCampaignLoanStatusTriggerViewModel';
import { LELodasoftCommonModelsAdminEmailCampaignTaskStatusTriggerViewModel } from '../definitions/LELodasoftCommonModelsAdminEmailCampaignTaskStatusTriggerViewModel';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsAdminEmailCampaignViewModel = {
    emailCampaignId: Option<number>;
    emailCampaignName: Option<string>;
    repeatDays: Option<number>;
    active: Option<boolean>;
    triggers: Option<Array<LELodasoftCommonModelsAdminEmailCampaignLoanStatusTriggerViewModel>>;
    taskStatusTriggers: Option<Array<LELodasoftCommonModelsAdminEmailCampaignTaskStatusTriggerViewModel>>;
    automatedEmails: Option<Array<LELodasoftCommonModelsAdminAutomatedEmailViewModel>>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsAdminEmailCampaignViewModelIO: import("io-ts").TypeC<{
    emailCampaignId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    emailCampaignName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    repeatDays: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    active: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    triggers: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").TypeC<{
        emailCampaignLoanStatusTriggerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        emailCampaignId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        loanPurposeId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        loanStatusId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        loanTypeId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    }>>>;
    taskStatusTriggers: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").TypeC<{
        emailCampaignTaskStatusTriggerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        emailCampaignId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        taskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        customTaskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        taskStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    }>>>;
    automatedEmails: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").TypeC<{
        automatedEmailId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        emailCampaignId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        emailTemplateId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        delayDays: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        daysOfWeekToSend: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        timeOfDayToSend: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        from: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        sendFromLoanContact: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        to: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        cc: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        bcc: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        subject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        appendLoanContactEmailSignature: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        active: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    }>>>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
