"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsPipelinePipelineApplicationViewIO = io_ts_1.type({
    primaryBorrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    applicationId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    lastName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    firstName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateCreateBorrower: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    refNumber: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingStreet: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingCity: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingState: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingZip: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    loanAmount: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanStatusId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanStatusName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    loanPurposeId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanPurposeName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    loanTypeId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanTypeName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    userId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    showAsArchive: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    hideFromCounter: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    appCreateDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    lockExpirationDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    estimatedClosingDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    cdIssueDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    cdSignedDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    originationDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    primaryRoleContact: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    primaryRoleContactId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    primaryRoleName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    lenderName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    loanStatusChangedDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftCommonModelsPipelinePipelineApplicationView.js.map