import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsThirdPartyFormFreeHistoryViewModel = {
    formFreeHistoryId: Option<number>;
    firstName: Option<string>;
    lastName: Option<string>;
    email: Option<string>;
    last4Ssn: Option<string>;
    voaRequestType: Option<'full' | 'lite'>;
    transactionId: Option<string>;
    accountChekOrderId: Option<string>;
    reportId: Option<string>;
    orderStatus: Option<number>;
    loginUrl: Option<string>;
    status: Option<string>;
    leadId: Option<number>;
    applicationId: Option<number>;
    borrowerId: Option<number>;
    loanDocTaskId: Option<number>;
    taskStatus: Option<'Pending' | 'Submitted' | 'Rejected' | 'Approved' | 'NotApplicable' | 'Requested' | 'Completed' | 'ReviewReady'>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsThirdPartyFormFreeHistoryViewModelIO: import("io-ts").TypeC<{
    formFreeHistoryId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    firstName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    lastName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    email: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    last4Ssn: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    voaRequestType: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        full: null;
        lite: null;
    }>>;
    transactionId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    accountChekOrderId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    reportId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    orderStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    loginUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    status: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    leadId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    applicationId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    borrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    loanDocTaskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    taskStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        Pending: null;
        Submitted: null;
        Rejected: null;
        Approved: null;
        NotApplicable: null;
        Requested: null;
        Completed: null;
        ReviewReady: null;
    }>>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
