import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsLeadsLeadCreditViewModel = {
    leadCreditId: Option<number>;
    leadId: Option<number>;
    creditRunDate: Option<Date>;
    experianScore: Option<number>;
    equifaxScore: Option<number>;
    transUnionScore: Option<number>;
    isJoint: Option<boolean>;
    referenceNumber: Option<string>;
    notes: Option<string>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsLeadsLeadCreditViewModelIO: import("io-ts").TypeC<{
    leadCreditId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    leadId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    creditRunDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    experianScore: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    equifaxScore: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    transUnionScore: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    isJoint: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    referenceNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    notes: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
