import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftDataAccessModelsAdminBorrowerBorrowerDto = {
    borrowerId: Option<number>;
    companyId: Option<number>;
    creditScore: Option<number>;
    firstName: Option<string>;
    lastName: Option<string>;
    last4Ssn: Option<string>;
    userId: Option<string>;
    phone: Option<string>;
    email: Option<string>;
    isRegister: Option<boolean>;
    isInvited: Option<boolean>;
    isPrimary: Option<boolean>;
    isPortalMerged: Option<boolean>;
    applicationId: Option<number>;
    lastTimeLogin: Option<Date>;
    birthDate: Option<Date>;
    mailingStreet: Option<string>;
    mailingCity: Option<string>;
    mailingState: Option<string>;
    mailingZip: Option<string>;
    borrowerContact: Option<string>;
    creditMonitoringStatus: Option<'Unset' | 'Active' | 'Disabled'>;
    dateCreateBorrower: Option<Date>;
};
export declare const LELodasoftDataAccessModelsAdminBorrowerBorrowerDtoIO: import("io-ts").TypeC<{
    borrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    creditScore: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    firstName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    lastName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    last4Ssn: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    phone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    email: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    isRegister: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    isInvited: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    isPrimary: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    isPortalMerged: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    applicationId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    lastTimeLogin: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    birthDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    mailingStreet: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingCity: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingState: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingZip: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    borrowerContact: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    creditMonitoringStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        Unset: null;
        Active: null;
        Disabled: null;
    }>>;
    dateCreateBorrower: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
