"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsMessageMessageHistoryViewModelIO = io_ts_1.type({
    extendedDetail: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    id: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    campaignId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    automatedEmailId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    applicationId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    borrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    agentId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    eventId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    leadId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    fromUserId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    msgType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Unspecified: null,
        UserInvite: null,
        BorrowerInvite: null,
        AgentInvite: null,
        ForgotPassword: null,
        DocRequest: null,
        DocReject: null,
        DocAccepted: null,
        StatusUpdate: null,
        Reminder: null,
        ApplicationEmailCampaign: null,
        ContactEmailCampaign: null,
        NewMessage: null,
        UserCreatedEmail: null,
        UserCreatedSms: null,
        Test: null,
        AppointmentAlert: null,
        Referral: null,
        CombinedParent: null,
    })),
    delivery: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ Unspecified: null, Email: null, SMS: null, Toaster: null })),
    priority: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ Unspecified: null, Immediate: null, Queue: null, QueuedImmediate: null, Retry: null })),
    status: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Unprocessed: null,
        InProcess: null,
        FailureSmsNotEnabled: null,
        Failure: null,
        Success: null,
        CombinedChild: null,
    })),
    to: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    from: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    cc: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    bcc: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    subject: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    body: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    trackingGuid: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    originalOpenDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    mostRecentOpenDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    createDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    lastUpdate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insertedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    updatedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateUpdated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftCommonModelsMessageMessageHistoryViewModel.js.map