"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LELodasoftApiModelsSharedIntegrationsModel_1 = require("../definitions/LELodasoftApiModelsSharedIntegrationsModel");
var LELodasoftCommonModelsConfigurationConfigurationViewModel_1 = require("../definitions/LELodasoftCommonModelsConfigurationConfigurationViewModel");
var LELodasoftCommonModelsEmailDefinedEmailTemplateViewModel_1 = require("../definitions/LELodasoftCommonModelsEmailDefinedEmailTemplateViewModel");
var LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModel_1 = require("../definitions/LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModel");
var LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModel_1 = require("../definitions/LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModel");
var LELodasoftDataAccessDbModelsSharedEmailServiceModel_1 = require("../definitions/LELodasoftDataAccessDbModelsSharedEmailServiceModel");
var LELodasoftDataAccessDbModelsSharedSmsServiceModel_1 = require("../definitions/LELodasoftDataAccessDbModelsSharedSmsServiceModel");
var LELodasoftDataAccessDbModelsUserProfile_1 = require("../definitions/LELodasoftDataAccessDbModelsUserProfile");
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftApiModelsUserProfileModelIO = io_ts_1.type({
    userProfile: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsUserProfile_1.LELodasoftDataAccessDbModelsUserProfileIO),
    integrations: io_ts_types_1.createOptionFromNullable(LELodasoftApiModelsSharedIntegrationsModel_1.LELodasoftApiModelsSharedIntegrationsModelIO),
    thirdPartyCredentials: io_ts_types_1.createOptionFromNullable(io_ts_1.array(LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModel_1.LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModelIO)),
    emailService: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsSharedEmailServiceModel_1.LELodasoftDataAccessDbModelsSharedEmailServiceModelIO),
    smsService: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsSharedSmsServiceModel_1.LELodasoftDataAccessDbModelsSharedSmsServiceModelIO),
    userName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    reminderEmailEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    reminderEmailInterval: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    reminderSmsEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    reminderSmsInterval: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    definedEmailTemplate: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsEmailDefinedEmailTemplateViewModel_1.LELodasoftCommonModelsEmailDefinedEmailTemplateViewModelIO),
    definedSmsTemplate: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModel_1.LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModelIO),
});
//# sourceMappingURL=LELodasoftApiModelsUserProfileModel.js.map