import { LELodasoftDataAccessDbModelsConfigurationCompanyModel } from '../definitions/LELodasoftDataAccessDbModelsConfigurationCompanyModel';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftDataAccessDbModelsAdminStackingOrderModel = {
    stakingOrderId: Option<number>;
    companyId: Option<number>;
    company: Option<LELodasoftDataAccessDbModelsConfigurationCompanyModel>;
    docType: Option<string>;
    associate: Option<string>;
};
export declare const LELodasoftDataAccessDbModelsAdminStackingOrderModelIO: import("io-ts").TypeC<{
    stakingOrderId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    company: import("io-ts-types").OptionFromNullableC<import("io-ts").TypeC<{
        companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        companyURL: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        borrowerURL: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        agentURL: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        companyGUID: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        companyName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        address: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        city: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        state: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        zip: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        logo: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        smallLogo: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        signatureLogo: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        nmls: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        isTemplate: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        docEditingEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        docGenerationEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        full1003Enabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        leadManagementEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        onlineApplicationEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        digitalAssetVerificationEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        digitalEmploymentVerificationEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        prequalGenerationEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        smsAlertsEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        emailTestsEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        inviteBorrowerCheckedByDefault: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        creditMonitoringEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        creditReportingEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        ausEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        losEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
        multipleCredentialSupportEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    }>>;
    docType: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    associate: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
}>;
