import { LELodasoftCommonModelsAdminEmailTemplateImageViewModel } from '../definitions/LELodasoftCommonModelsAdminEmailTemplateImageViewModel';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsEmailDefinedEmailTemplateViewModel = {
    id: Option<number>;
    userId: Option<string>;
    onlineAppRegistrationOverride: Option<boolean>;
    onlineAppRegistrationSubject: Option<string>;
    onlineAppRegistrationEmail: Option<string>;
    onlineAppStartedOverride: Option<boolean>;
    onlineAppStartedSubject: Option<string>;
    onlineAppStartedEmail: Option<string>;
    onlineAppSubmissionOverride: Option<boolean>;
    onlineAppSubmissionSubject: Option<string>;
    onlineAppSubmissionEmail: Option<string>;
    inviteOverride: Option<boolean>;
    inviteSubject: Option<string>;
    inviteEmail: Option<string>;
    inviteAgentOverride: Option<boolean>;
    inviteAgentSubject: Option<string>;
    inviteAgentEmail: Option<string>;
    requestOverride: Option<boolean>;
    requestSubject: Option<string>;
    requestEmail: Option<string>;
    reminderOverride: Option<boolean>;
    reminderSubject: Option<string>;
    reminderEmail: Option<string>;
    images: Option<Array<LELodasoftCommonModelsAdminEmailTemplateImageViewModel>>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsEmailDefinedEmailTemplateViewModelIO: import("io-ts").TypeC<{
    id: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    onlineAppRegistrationOverride: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    onlineAppRegistrationSubject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    onlineAppRegistrationEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    onlineAppStartedOverride: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    onlineAppStartedSubject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    onlineAppStartedEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    onlineAppSubmissionOverride: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    onlineAppSubmissionSubject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    onlineAppSubmissionEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    inviteOverride: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    inviteSubject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    inviteEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    inviteAgentOverride: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    inviteAgentSubject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    inviteAgentEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    requestOverride: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    requestSubject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    requestEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    reminderOverride: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    reminderSubject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    reminderEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    images: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").TypeC<{
        emailTemplateImageId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        emailTemplateImageGuid: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        definedEmailTemplateId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        emailTemplateId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        mimeType: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        imageData: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
        updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    }>>>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
