"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsLeadsUserProfileViewModelIO = io_ts_1.type({
    id: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    stackOrderId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    roleId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    userName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    userType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ Admin: null, Borrower: null, Agent: null })),
    avatarId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    firstName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    lastName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    timeZone: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    title: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    nmls: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    emailSignature: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    smsSignature: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    flagAdmin: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    reportTo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    inviteDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    confirmationDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    twoFactorEnabled: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    email: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    emailConfirmed: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    phoneNumber: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    phoneNumberConfirmed: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    cellPhone: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    workPhone: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    homePhone: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    fax: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingStreet: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingPOBox: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingCity: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingState: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mailingZip: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    active: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
});
//# sourceMappingURL=LELodasoftCommonModelsLeadsUserProfileViewModel.js.map