import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsLeadsUserProfileViewModel = {
    id: Option<string>;
    companyId: Option<number>;
    stackOrderId: Option<number>;
    roleId: Option<number>;
    userName: Option<string>;
    userType: Option<'Admin' | 'Borrower' | 'Agent'>;
    avatarId: Option<string>;
    firstName: Option<string>;
    lastName: Option<string>;
    timeZone: Option<string>;
    title: Option<string>;
    nmls: Option<string>;
    emailSignature: Option<string>;
    smsSignature: Option<string>;
    flagAdmin: Option<boolean>;
    reportTo: Option<string>;
    inviteDate: Option<Date>;
    confirmationDate: Option<Date>;
    twoFactorEnabled: Option<boolean>;
    email: Option<string>;
    emailConfirmed: Option<boolean>;
    phoneNumber: Option<string>;
    phoneNumberConfirmed: Option<boolean>;
    cellPhone: Option<string>;
    workPhone: Option<string>;
    homePhone: Option<string>;
    fax: Option<string>;
    mailingStreet: Option<string>;
    mailingPOBox: Option<string>;
    mailingCity: Option<string>;
    mailingState: Option<string>;
    mailingZip: Option<string>;
    active: Option<boolean>;
};
export declare const LELodasoftCommonModelsLeadsUserProfileViewModelIO: import("io-ts").TypeC<{
    id: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    stackOrderId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    roleId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    userName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    userType: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        Admin: null;
        Borrower: null;
        Agent: null;
    }>>;
    avatarId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    firstName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    lastName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    timeZone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    title: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    nmls: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    emailSignature: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    smsSignature: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    flagAdmin: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    reportTo: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    inviteDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    confirmationDate: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    twoFactorEnabled: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    email: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    emailConfirmed: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    phoneNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    phoneNumberConfirmed: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    cellPhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    workPhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    homePhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    fax: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingStreet: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingPOBox: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingCity: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingState: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mailingZip: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    active: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
}>;
