"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LELodasoftApiModelsSharedIntegrationsModel_1 = require("../definitions/LELodasoftApiModelsSharedIntegrationsModel");
var LELodasoftCommonModelsConfigurationConfigurationViewModel_1 = require("../definitions/LELodasoftCommonModelsConfigurationConfigurationViewModel");
var LELodasoftCommonModelsEmailDefinedEmailTemplateViewModel_1 = require("../definitions/LELodasoftCommonModelsEmailDefinedEmailTemplateViewModel");
var LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModel_1 = require("../definitions/LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModel");
var LELodasoftDataAccessDbModelsConfigurationAgentPortalContentModel_1 = require("../definitions/LELodasoftDataAccessDbModelsConfigurationAgentPortalContentModel");
var LELodasoftDataAccessDbModelsConfigurationBorrowerPortalContentModel_1 = require("../definitions/LELodasoftDataAccessDbModelsConfigurationBorrowerPortalContentModel");
var LELodasoftDataAccessDbModelsConfigurationCompanyModel_1 = require("../definitions/LELodasoftDataAccessDbModelsConfigurationCompanyModel");
var LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModel_1 = require("../definitions/LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModel");
var LELodasoftDataAccessDbModelsConfigurationPrequalGenerationSettingsModel_1 = require("../definitions/LELodasoftDataAccessDbModelsConfigurationPrequalGenerationSettingsModel");
var LELodasoftDataAccessDbModelsSharedEmailServiceModel_1 = require("../definitions/LELodasoftDataAccessDbModelsSharedEmailServiceModel");
var LELodasoftDataAccessDbModelsSharedSmsServiceModel_1 = require("../definitions/LELodasoftDataAccessDbModelsSharedSmsServiceModel");
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftApiModelsAdminSystemLevelIO = io_ts_1.type({
    sessionTimeout: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    reminderEmailEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    reminderEmailInterval: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    reminderSmsEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    reminderSmsInterval: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    documentExportFormat: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    digitalAssetVerificationEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    digitalEmploymentVerificationEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    creditReportingEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    ausEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    losEnabled: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    defaultCreditVendor: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsConfigurationConfigurationViewModel_1.LELodasoftCommonModelsConfigurationConfigurationViewModelIO),
    prequalGenerationSettings: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsConfigurationPrequalGenerationSettingsModel_1.LELodasoftDataAccessDbModelsConfigurationPrequalGenerationSettingsModelIO),
    definedEmailTemplate: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsEmailDefinedEmailTemplateViewModel_1.LELodasoftCommonModelsEmailDefinedEmailTemplateViewModelIO),
    definedSmsTemplate: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModel_1.LELodasoftDataAccessDbModelsConfigurationDefinedSmsTemplateModelIO),
    borrowerPortalContent: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsConfigurationBorrowerPortalContentModel_1.LELodasoftDataAccessDbModelsConfigurationBorrowerPortalContentModelIO),
    agentPortalContent: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsConfigurationAgentPortalContentModel_1.LELodasoftDataAccessDbModelsConfigurationAgentPortalContentModelIO),
    emailService: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsSharedEmailServiceModel_1.LELodasoftDataAccessDbModelsSharedEmailServiceModelIO),
    smsService: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsSharedSmsServiceModel_1.LELodasoftDataAccessDbModelsSharedSmsServiceModelIO),
    integrations: io_ts_types_1.createOptionFromNullable(LELodasoftApiModelsSharedIntegrationsModel_1.LELodasoftApiModelsSharedIntegrationsModelIO),
    thirdPartyCredentials: io_ts_types_1.createOptionFromNullable(io_ts_1.array(LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModel_1.LELodasoftCommonModelsThirdPartyThirdPartyCredentialsViewModelIO)),
    company: io_ts_types_1.createOptionFromNullable(LELodasoftDataAccessDbModelsConfigurationCompanyModel_1.LELodasoftDataAccessDbModelsConfigurationCompanyModelIO),
});
//# sourceMappingURL=LELodasoftApiModelsAdminSystemLevel.js.map