import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsConfigurationWizardWizardConfigViewModel = {
    id: Option<number>;
    name: Option<string>;
    dataId: Option<string>;
    data: Option<string>;
    groupId: Option<string>;
    group: Option<string>;
    valid: Option<string>;
    tree: Option<string>;
    questionId: Option<string>;
    startUrl: Option<string>;
    postUrl: Option<string>;
    answersModelJSON: Option<string>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsConfigurationWizardWizardConfigViewModelIO: import("io-ts").TypeC<{
    id: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    name: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dataId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    data: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    groupId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    group: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    valid: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    tree: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    questionId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    startUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    postUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    answersModelJSON: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
