"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LELodasoftDataAccessModelsAdminBorrowerFileDto_1 = require("../definitions/LELodasoftDataAccessModelsAdminBorrowerFileDto");
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftApiModelsBorrowerLoanDocTask_DashBoardViewIO = io_ts_1.type({
    loanDocTaskId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    applicationId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    leadId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanDocId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    primaryBorrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    borrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    fullName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    applicationName: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    taskId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    customTaskId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    responsibleParty: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    requestedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    note: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    status: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Pending: null,
        Submitted: null,
        Rejected: null,
        Approved: null,
        NotApplicable: null,
        Requested: null,
        Completed: null,
        ReviewReady: null,
    })),
    taskStatus: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    taskPriority: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ Low: null, Normal: null, High: null, Immediate: null })),
    taskType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        RequestDocument: null,
        ViewDocument: null,
        AcknowledgeReceipt: null,
        EsignDocument: null,
        RequestInformation: null,
        PerformAction: null,
        OnlineApplication: null,
        DigitalAssetVerification: null,
    })),
    documentTypeId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    docTypeText: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    description: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dueDays: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    requestDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    dueDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    followUp: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    completeDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    submittedDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    expirationDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    userId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    roleId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    requestBorrower: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    loading: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    borrowerNote: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    condition: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    conditionStatus: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ ConditionPending: null, ConditionCleared: null, ConditionReOpened: null })),
    conditionType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ PTS: null, PTD: null, PTF: null, PTC: null })),
    docFiles: io_ts_types_1.createOptionFromNullable(io_ts_1.array(LELodasoftDataAccessModelsAdminBorrowerFileDto_1.LELodasoftDataAccessModelsAdminBorrowerFileDtoIO)),
    notifyPartyId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    requiresReview: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    reviewPartyId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    borrowerFacingNote: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    hasTemplateDocument: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    templateDocumentUrl: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
});
//# sourceMappingURL=LELodasoftApiModelsBorrowerLoanDocTask_DashBoardView.js.map