"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsAdminActivityLogViewModelIO = io_ts_1.type({
    userId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    category: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ LoanChangeStatus: null, BorrowerMessage: null, InternalMessage: null, Lead: null, DocumentFile: null })),
    activityType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        LoanChangeStatus: null,
        BorrowerMessage: null,
        InternalMessage: null,
        LeadNote: null,
        LeadEmail: null,
        LeadSms: null,
        LeadPhoneAttempt: null,
        LeadPhoneSuccess: null,
        ChangeStatus: null,
        Uploadfile: null,
        DeleteFile: null,
        DownloadFile: null,
        ExportFile: null,
        FileNoteUpdated: null,
        BorrowerNoteUpdated: null,
        DeleteTask: null,
        RemoveFileFromTrash: null,
        ConditionStatusChange: null,
        CreateTask: null,
        RestoreTask: null,
        MergeFile: null,
        PostponeTask: null,
        ChangeFollowUpDate: null,
        ChangeDueDate: null,
        ViewFile: null,
        FileNameChanged: null,
        ChangeConditionFlag: null,
        ChangeDescription: null,
        ChangeNotifyParty: null,
        ChangePriority: null,
        ChangeResponsibleParty: null,
        ChangeReviewRequired: null,
        Unknown: null,
    })),
    displayText: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateCreated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    loanDocTaskId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    messageId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    leadEventId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    fileId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    trackingId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
});
//# sourceMappingURL=LELodasoftCommonModelsAdminActivityLogViewModel.js.map