import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsAdminMessageViewModel = {
    messageId: Option<number>;
    applicationId: Option<number>;
    loanDocTaskId: Option<number>;
    borrowerId: Option<number>;
    userId: Option<string>;
    content: Option<string>;
    flagInternalMessage: Option<boolean>;
    postTime: Option<Date>;
    senderId: Option<string>;
    senderFirstName: Option<string>;
    senderLastName: Option<string>;
    senderAvatar: Option<string>;
    notifyPartyId: Option<Array<string>>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsAdminMessageViewModelIO: import("io-ts").TypeC<{
    messageId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    applicationId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    loanDocTaskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    borrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    content: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    flagInternalMessage: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    postTime: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    senderId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    senderFirstName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    senderLastName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    senderAvatar: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    notifyPartyId: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").StringC>>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
