import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsMortgagePurchaseCreditViewModel = {
    purchaseCreditId: Option<number>;
    transactionDetailId: Option<number>;
    purchaseCreditType: Option<'BridgeLoan' | 'CashOnHand' | 'CheckingSavings' | 'DepositOnSalesContract' | 'EquityOnPendingSale' | 'EquityOnSoldProperty' | 'EquityOnSubjectProperty' | 'GiftFunds' | 'LifeInsuranceCashValue' | 'LotEquity' | 'OtherTypeOfDownPayment' | 'RentWithOptionToPurchase' | 'RetirementFunds' | 'SaleOfChattel' | 'SecuredBorrowedFunds' | 'StocksAndBonds' | 'SweatEquity' | 'TradeEquity' | 'TrustFunds' | 'UnsecuredBorrowedFunds' | 'EarnestMoney' | 'RelocationFunds' | 'EmployerAssistedHousing' | 'LeasePurchaseFund' | 'Other' | 'LenderCredit'>;
    purchaseCreditAmount: Option<number>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsMortgagePurchaseCreditViewModelIO: import("io-ts").TypeC<{
    purchaseCreditId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    transactionDetailId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    purchaseCreditType: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        BridgeLoan: null;
        CashOnHand: null;
        CheckingSavings: null;
        DepositOnSalesContract: null;
        EquityOnPendingSale: null;
        EquityOnSoldProperty: null;
        EquityOnSubjectProperty: null;
        GiftFunds: null;
        LifeInsuranceCashValue: null;
        LotEquity: null;
        OtherTypeOfDownPayment: null;
        RentWithOptionToPurchase: null;
        RetirementFunds: null;
        SaleOfChattel: null;
        SecuredBorrowedFunds: null;
        StocksAndBonds: null;
        SweatEquity: null;
        TradeEquity: null;
        TrustFunds: null;
        UnsecuredBorrowedFunds: null;
        EarnestMoney: null;
        RelocationFunds: null;
        EmployerAssistedHousing: null;
        LeasePurchaseFund: null;
        Other: null;
        LenderCredit: null;
    }>>;
    purchaseCreditAmount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
