"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LELodasoftCommonModelsMortgageEmploymentViewModel_1 = require("../definitions/LELodasoftCommonModelsMortgageEmploymentViewModel");
var LELodasoftCommonModelsMortgageReoViewModel_1 = require("../definitions/LELodasoftCommonModelsMortgageReoViewModel");
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsMortgageIncomeViewModelIO = io_ts_1.type({
    incomeId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    borrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    employmentId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    employmentModel: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsMortgageEmploymentViewModel_1.LELodasoftCommonModelsMortgageEmploymentViewModelIO),
    reoId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    reoModel: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsMortgageReoViewModel_1.LELodasoftCommonModelsMortgageReoViewModelIO),
    monthlyIncome: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    typeOfIncome: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        AlimonyChildSupport: null,
        AutomobileExpenseAccount: null,
        Base: null,
        Bonus: null,
        Commissions: null,
        DividendsInterest: null,
        EmploymentIncome: null,
        FosterCare: null,
        NetRentalIncome: null,
        NotesReceivableInstallment: null,
        OtherTypesOfIncome: null,
        Overtime: null,
        Pension: null,
        SocialSecurity: null,
        SubjectPropertyNetCashFlow: null,
        Trust: null,
        Unemployment: null,
        PublicAssistance: null,
        VABenefitsNonEducational: null,
        MortgageDifferential: null,
        MilitaryBasePay: null,
        MilitaryRationsAllowance: null,
        MilitaryFlightPay: null,
        MilitaryHazardPay: null,
        MilitaryClothesAllowance: null,
        MilitaryQuartersAllowance: null,
        MilitaryPropPay: null,
        MilitaryOverseasPay: null,
        MilitaryCombatPay: null,
        MilitaryVariableHousingAllowance: null,
        SelfEmployment: null,
        IndependentContractor: null,
    })),
    categoryOfIncome: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Employment: null,
        IndependentContractor: null,
        MilitaryPay: null,
        Rental: null,
        SocialSecurity: null,
        Pension: null,
        BuisnessSelfEmployment: null,
        Other: null,
    })),
    fromCreditReport: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insertedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    updatedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateUpdated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftCommonModelsMortgageIncomeViewModel.js.map