import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsAdminActivityLogViewModel = {
    userId: Option<string>;
    category: Option<'LoanChangeStatus' | 'BorrowerMessage' | 'InternalMessage' | 'Lead' | 'DocumentFile'>;
    activityType: Option<'LoanChangeStatus' | 'BorrowerMessage' | 'InternalMessage' | 'LeadNote' | 'LeadEmail' | 'LeadSms' | 'LeadPhoneAttempt' | 'LeadPhoneSuccess' | 'ChangeStatus' | 'Uploadfile' | 'DeleteFile' | 'DownloadFile' | 'ExportFile' | 'FileNoteUpdated' | 'BorrowerNoteUpdated' | 'DeleteTask' | 'RemoveFileFromTrash' | 'ConditionStatusChange' | 'CreateTask' | 'RestoreTask' | 'MergeFile' | 'PostponeTask' | 'ChangeFollowUpDate' | 'ChangeDueDate' | 'ViewFile' | 'FileNameChanged' | 'ChangeConditionFlag' | 'ChangeDescription' | 'ChangeNotifyParty' | 'ChangePriority' | 'ChangeResponsibleParty' | 'ChangeReviewRequired' | 'Unknown'>;
    displayText: Option<string>;
    dateCreated: Option<Date>;
    loanDocTaskId: Option<number>;
    messageId: Option<number>;
    leadEventId: Option<number>;
    fileId: Option<string>;
    trackingId: Option<number>;
};
export declare const LELodasoftCommonModelsAdminActivityLogViewModelIO: import("io-ts").TypeC<{
    userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    category: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        LoanChangeStatus: null;
        BorrowerMessage: null;
        InternalMessage: null;
        Lead: null;
        DocumentFile: null;
    }>>;
    activityType: import("io-ts-types").OptionFromNullableC<import("io-ts").KeyofC<{
        LoanChangeStatus: null;
        BorrowerMessage: null;
        InternalMessage: null;
        LeadNote: null;
        LeadEmail: null;
        LeadSms: null;
        LeadPhoneAttempt: null;
        LeadPhoneSuccess: null;
        ChangeStatus: null;
        Uploadfile: null;
        DeleteFile: null;
        DownloadFile: null;
        ExportFile: null;
        FileNoteUpdated: null;
        BorrowerNoteUpdated: null;
        DeleteTask: null;
        RemoveFileFromTrash: null;
        ConditionStatusChange: null;
        CreateTask: null;
        RestoreTask: null;
        MergeFile: null;
        PostponeTask: null;
        ChangeFollowUpDate: null;
        ChangeDueDate: null;
        ViewFile: null;
        FileNameChanged: null;
        ChangeConditionFlag: null;
        ChangeDescription: null;
        ChangeNotifyParty: null;
        ChangePriority: null;
        ChangeResponsibleParty: null;
        ChangeReviewRequired: null;
        Unknown: null;
    }>>;
    displayText: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateCreated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    loanDocTaskId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    messageId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    leadEventId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    fileId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    trackingId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
}>;
