import { LELodasoftCommonModelsSharedBorrowerView } from '../definitions/LELodasoftCommonModelsSharedBorrowerView';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsSharedApplicationView = {
    applicationId: Option<number>;
    refNumber: Option<string>;
    streetViewImageUrl: Option<string>;
    mapViewImageUrl: Option<string>;
    address: Option<string>;
    city: Option<string>;
    state: Option<string>;
    zip: Option<string>;
    loanStatus: Option<string>;
    blurb: Option<string>;
    loanPurpose: Option<string>;
    loanAmount: Option<number>;
    interestRate: Option<number>;
    contactRole: Option<string>;
    contactName: Option<string>;
    contactNumber: Option<string>;
    companyId: Option<number>;
    companyName: Option<string>;
    applicationName: Option<string>;
    onlineAppInProgress: Option<boolean>;
    forceFinishOnlineApp: Option<boolean>;
    myDetails: Option<LELodasoftCommonModelsSharedBorrowerView>;
    otherBorrowersOnLoan: Option<Array<LELodasoftCommonModelsSharedBorrowerView>>;
};
export declare const LELodasoftCommonModelsSharedApplicationViewIO: import("io-ts").TypeC<{
    applicationId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    refNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    streetViewImageUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    mapViewImageUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    address: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    city: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    state: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    zip: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    loanStatus: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    blurb: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    loanPurpose: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    loanAmount: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    interestRate: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    contactRole: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    contactName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    contactNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    companyName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    applicationName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    onlineAppInProgress: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    forceFinishOnlineApp: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    myDetails: import("io-ts-types").OptionFromNullableC<import("io-ts").TypeC<{
        borrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        borrowerName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        borrowerPhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        borrowerEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    }>>;
    otherBorrowersOnLoan: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").TypeC<{
        borrowerId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
        borrowerName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        borrowerPhone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        borrowerEmail: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    }>>>;
}>;
