"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsMortgageDeclarationViewModelIO = io_ts_1.type({
    declarationId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    borrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    haveJudgement: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    haveJudgementInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    declaredBankruptcy: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    declaredBankruptcyInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    beenForclosed: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    beenForclosedInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    haveLawsuit: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    haveLawsuitInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    haveLoanObligation: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    haveLoanObligationInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    haveTaxDebt: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    haveTaxDebtInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    haveChildSupport: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    haveChildSupportInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    borrowedDownPayment: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    borrowedDownPaymentInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    coSignedLoan: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    coSignedLoanInfo: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    isVeteran: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    residenceStatus: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ USCitizen: null, PermanentResident: null, ResidentAlien: null, UnknownResidencyStatus: null })),
    occupyProperty: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    havePropertiesOwnership: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    typeOfProperty: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        SFRAttached: null,
        Condominium: null,
        Cooperative: null,
        SFR: null,
        HighRiseCondominium: null,
        ManufacturedHousing: null,
        Modular: null,
        PUD: null,
        ManufacturedHousingSingleWide: null,
        ManufacturedHousingDoubleWide: null,
        DetachedCondominium: null,
        ManufacturedHomeCondominium: null,
        ManufacturedHousingMultiWide: null,
        ManufacturedHomeCondominiumOrPUDOrCooperative: null,
        TwoTo4UnitBuilding: null,
        NonWarrantedCondo: null,
    })),
    propertyWillBe: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ PrimaryResidence: null, SecondaryResidence: null, Investment: null, ShortTermRental: null })),
    heldTitleHow: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    fromCreditReport: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insertedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    updatedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateUpdated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftCommonModelsMortgageDeclarationViewModel.js.map