"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftDataAccessDbModelsAdminLoanDocTaskModelIO = io_ts_1.type({
    loanDocTaskId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    leadId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    applicationId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    borrowerId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    taskId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    customTaskId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    loanDocId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    documentTypeId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    userId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    roleId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    notifyPartyId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    reviewPartyId: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    taskType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        RequestDocument: null,
        ViewDocument: null,
        AcknowledgeReceipt: null,
        EsignDocument: null,
        RequestInformation: null,
        PerformAction: null,
        OnlineApplication: null,
        DigitalAssetVerification: null,
    })),
    taskPriority: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ Low: null, Normal: null, High: null, Immediate: null })),
    description: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    note: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    borrowerFacingNote: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    requestedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dueDays: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    taskStatus: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Pending: null,
        Submitted: null,
        Rejected: null,
        Approved: null,
        NotApplicable: null,
        Requested: null,
        Completed: null,
        ReviewReady: null,
    })),
    conditionStatus: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ ConditionPending: null, ConditionCleared: null, ConditionReOpened: null })),
    conditionType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ PTS: null, PTD: null, PTF: null, PTC: null })),
    requestBorrower: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    condition: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    requiresReview: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    requestDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    dueDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    submittedDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    acknowledgementDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    completeDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    followUpDate: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    active: io_ts_types_1.createOptionFromNullable(io_ts_1.boolean),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insertedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    updatedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateUpdated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftDataAccessDbModelsAdminLoanDocTaskModel.js.map