import { LELodasoftCommonModelsMortgageAddressViewModel } from '../definitions/LELodasoftCommonModelsMortgageAddressViewModel';
import { LELodasoftCommonModelsMortgageIncomeViewModel } from '../definitions/LELodasoftCommonModelsMortgageIncomeViewModel';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsMortgageEmploymentViewModel = {
    employmentId: Option<number>;
    borrowerId: Option<number>;
    addressId: Option<number>;
    employer: Option<string>;
    employerEmail: Option<string>;
    employerPhone: Option<string>;
    employmentType: Option<'CurrentEmployer' | 'FormerEmployer'>;
    selfEmployed: Option<boolean>;
    isPrimary: Option<boolean>;
    position: Option<string>;
    startDate: Option<Date>;
    endDate: Option<Date>;
    yearsOnJob: Option<number>;
    monthsOnJob: Option<number>;
    yearsInLineOfWork: Option<number>;
    fromCreditReport: Option<boolean>;
    address: Option<LELodasoftCommonModelsMortgageAddressViewModel>;
    incomes: Option<Array<LELodasoftCommonModelsMortgageIncomeViewModel>>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsMortgageEmploymentViewModelIO: any;
