"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LELodasoftCommonModelsMortgageAddressViewModel_1 = require("../definitions/LELodasoftCommonModelsMortgageAddressViewModel");
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsMortgageSubjectPropertyViewModelIO = io_ts_1.type({
    subjectPropertyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    addressId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    purposeOfLoan: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Refinance: null,
        Purchase: null,
        ConstructionOnly: null,
        ConstructionToPermanent: null,
        OtherLoanPurpose: null,
        RefinanceCashOut: null,
    })),
    propertyWillBe: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ PrimaryResidence: null, SecondaryResidence: null, Investment: null, ShortTermRental: null })),
    noOfUnits: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    propertyType: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        SFRAttached: null,
        Condominium: null,
        Cooperative: null,
        SFR: null,
        HighRiseCondominium: null,
        ManufacturedHousing: null,
        Modular: null,
        PUD: null,
        ManufacturedHousingSingleWide: null,
        ManufacturedHousingDoubleWide: null,
        DetachedCondominium: null,
        ManufacturedHomeCondominium: null,
        ManufacturedHousingMultiWide: null,
        ManufacturedHomeCondominiumOrPUDOrCooperative: null,
        TwoTo4UnitBuilding: null,
        NonWarrantedCondo: null,
    })),
    yearBuilt: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    originalCost: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    amountOutstanding: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    presentValue: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    improvementCost: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    originalCostYear: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    amountExistLiensYear: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    refiPurpose: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({
        Purchase: null,
        RefinanceCashOut: null,
        RefinanceNoCashOut: null,
        StreamlinedRefinance: null,
        Construction: null,
    })),
    describeImprovement: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    improvementStatus: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ Made: null, ToBeMade: null })),
    cost: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    titleNames: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    explain: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    manner: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    estate: io_ts_types_1.createOptionFromNullable(io_ts_1.keyof({ FeeSimple: null, LeaseHold: null })),
    address: io_ts_types_1.createOptionFromNullable(LELodasoftCommonModelsMortgageAddressViewModel_1.LELodasoftCommonModelsMortgageAddressViewModelIO),
    companyId: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    insertedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateInserted: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
    updatedBy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    dateUpdated: io_ts_types_1.createOptionFromNullable(io_ts_types_1.DateFromISOString),
});
//# sourceMappingURL=LELodasoftCommonModelsMortgageSubjectPropertyViewModel.js.map