import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsAdminAutomatedEmailViewModel = {
    automatedEmailId: Option<number>;
    emailCampaignId: Option<number>;
    emailTemplateId: Option<number>;
    delayDays: Option<number>;
    daysOfWeekToSend: Option<string>;
    timeOfDayToSend: Option<string>;
    from: Option<string>;
    sendFromLoanContact: Option<boolean>;
    to: Option<string>;
    cc: Option<string>;
    bcc: Option<string>;
    subject: Option<string>;
    appendLoanContactEmailSignature: Option<boolean>;
    active: Option<boolean>;
    companyId: Option<number>;
    insertedBy: Option<string>;
    dateInserted: Option<Date>;
    updatedBy: Option<string>;
    dateUpdated: Option<Date>;
};
export declare const LELodasoftCommonModelsAdminAutomatedEmailViewModelIO: import("io-ts").TypeC<{
    automatedEmailId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    emailCampaignId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    emailTemplateId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    delayDays: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    daysOfWeekToSend: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    timeOfDayToSend: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    from: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    sendFromLoanContact: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    to: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    cc: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    bcc: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    subject: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    appendLoanContactEmailSignature: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    active: import("io-ts-types").OptionFromNullableC<import("io-ts").BooleanC>;
    companyId: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    insertedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateInserted: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
    updatedBy: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    dateUpdated: import("io-ts-types").OptionFromNullableC<import("io-ts-types").DateFromISOStringC>;
}>;
