"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var io_ts_1 = require("io-ts");
var io_ts_types_1 = require("io-ts-types");
exports.LELodasoftCommonModelsLeadsProviderModelsBestReferralLeadIO = io_ts_1.type({
    first_name: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    last_name: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    address: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    city: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    state: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    zip_code: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    email_address: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    phone_work: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    phone_home: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    phone_cell: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    best_time: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    ip_address: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    type_of_loan: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    home_value: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    mortgage_amount: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    property_description: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    credit_rating: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    loan_type: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    cash_out_request: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    current_interest_rate: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    down_payment: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    found_home: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    military_service: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    website: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    current_va: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    current_fha: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    months_late: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    improve_credit: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    realtor: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    property_purpose: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    mortgage_payment: io_ts_types_1.createOptionFromNullable(io_ts_1.number),
    bankruptcy: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    foreclosure: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    first_homebuyer: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    timeframe: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
    leadID: io_ts_types_1.createOptionFromNullable(io_ts_1.string),
});
//# sourceMappingURL=LELodasoftCommonModelsLeadsProviderModelsBestReferralLead.js.map