import { LELodasoftCommonModelsSharedLoanContact } from '../definitions/LELodasoftCommonModelsSharedLoanContact';
import { Option } from 'fp-ts/lib/Option';
export declare type LELodasoftCommonModelsAgentPortalAgentContact = {
    firstName: Option<string>;
    lastName: Option<string>;
    title: Option<string>;
    agentNMLS: Option<string>;
    agentAvatarUrl: Option<string>;
    agentAddressUrl: Option<string>;
    phoneNumber: Option<string>;
    faxNumber: Option<string>;
    emailAddress: Option<string>;
    companyName: Option<string>;
    companyUrl: Option<string>;
    companyNMLS: Option<string>;
    address: Option<string>;
    city: Option<string>;
    state: Option<string>;
    zip: Option<string>;
    loanContacts: Option<Array<LELodasoftCommonModelsSharedLoanContact>>;
};
export declare const LELodasoftCommonModelsAgentPortalAgentContactIO: import("io-ts").TypeC<{
    firstName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    lastName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    title: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    agentNMLS: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    agentAvatarUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    agentAddressUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    phoneNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    faxNumber: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    emailAddress: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    companyName: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    companyUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    companyNMLS: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    address: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    city: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    state: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    zip: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
    loanContacts: import("io-ts-types").OptionFromNullableC<import("io-ts").ArrayC<import("io-ts").TypeC<{
        userId: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        name: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        title: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        phone: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        email: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        avatarUrl: import("io-ts-types").OptionFromNullableC<import("io-ts").StringC>;
        order: import("io-ts-types").OptionFromNullableC<import("io-ts").NumberC>;
    }>>>;
}>;
